name: CI/CD

on:
   pull_request:
     branches: [main, develop]
     types: [opened, synchronize] 

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.start.outputs.timestamp }}
      selected-user: ${{ steps.select-user.outputs.selected_user }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set start timestamp
        id: start
        run: |
          printf 'timestamp=%(%s)T\n' >> "$GITHUB_OUTPUT"

      - name: Select the user with the fewest PR assignments
        id: select-user
        run: |
         const fs = require('fs');

         // Read environment variables
         const slackUsers = process.env.SLACK_USER_IDS.split(' ');
         const githubUsers = process.env.GH_USERS.split(' ');
         const currentActor = process.env.GITHUB_ACTOR;

         // Read and parse pr_assignments.json
         const prAssignments = JSON.parse(fs.readFileSync('pr_assignments.json', 'utf8'));

         // Initialize assignmentCounts from prAssignments
         const assignmentCounts = prAssignments || {};

         // Filter out the current GitHub actor from the list of GitHub users
         const filteredUsers = {};
         githubUsers.forEach((githubUser, index) => {
         if (githubUser !== currentActor) {
            const slackUserId = slackUsers[index];
            const prCount = assignmentCounts[slackUserId] || 0;
            filteredUsers[slackUserId] = prCount;
         }
         });

         // Sort the filteredUsers by PR count
         const sortedUsers = Object.keys(filteredUsers).sort((a, b) => filteredUsers[a] - filteredUsers[b]);

         // Select the user with the fewest PR assignments
         const selectedUser = sortedUsers[0];

         // Update the count for the selected user
         assignmentCounts[selectedUser] = (assignmentCounts[selectedUser] || 0) + 1;

         // Write the updated assignmentCounts back to pr_assignments.json
         fs.writeFileSync('pr_assignments.json', JSON.stringify(assignmentCounts, null, 2));

          echo "selected_user=$selected_user" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pr_assignments.json
          git commit -m "Update PR assignments"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}

  post-on-slack:
    runs-on: ubuntu-latest
    if: always()
    needs: [setup]
    steps:
      - name: Post to a Slack channel
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: '${{ vars.SLACK_CHANNEL_ID }}'
          payload: |
            {
               "blocks": [
                  {
                     "type": "context",
                     "elements": [
                        {
                           "type": "image",
                           "image_url": "https://avatars.githubusercontent.com/u/${{github.actor_id}}?s=400&u=b81e946713a585cd4895227203a3d2ba5d5b3b46&v=4",
                           "alt_text": "actor"
                        },
                        {
                           "type": "mrkdwn",
                           "text": "<https://github.com/${{github.actor}}|${{github.actor}}>"
                        }
                     ]
                  },
                  {
                     "type": "section",
                     "text": {
                        "type": "mrkdwn",
                        "text": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow # ${{ github.run_id }}>"
                     }
                  },
                  {
                     "type": "section",
                     "fields": [
                        {
                           "type": "mrkdwn",
                           "text": "*Repo*"
                        },
                        {
                           "type": "mrkdwn",
                           "text": "*Pull request*"
                        },
                        {
                           "type": "mrkdwn",
                           "text": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                        },
                        {
                           "type": "mrkdwn",
                           "text": "<${{ github.event.pull_request.html_url }}| Ver PR>"
                        }
                     ]
                  },
                  {
                     "type": "section",
                     "text": {
                        "type": "mrkdwn",
                        "text": "<@${{ needs.setup.outputs.selected-user }}> Por favor, revisa este pull request :${{ vars.PLEASE_EMOJI }}:"
                     }
                  },
                  {
                     "type": "section",
                     "fields": [
                        {
                           "type": "mrkdwn",
                           "text": "*Número de PRs revisados:*"
                        },
                        {
                           "type": "mrkdwn",
                           "text": "${{ needs.setup.outputs.selected-user }}: ${assignment_counts[$selected_user]}"
                        }
                     ]
                  },
                  {
                     "type": "divider"
                  }
               ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ vars.SLACK_BOT_TOKEN }}
