name: Check eslint configuration
on:
  pull_request:
    branches: [main, develop]
    types: [opened, reopened, synchronize, edited]

jobs:
  eslint-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.12.0

    - name: Install ESLint
      run: |
        yarn globall add eslint@8.5.0 eslint-config-google@0.14.0 eslint-plugin-jsdoc@46.8.2

    - name: Check ESLint configuration in settings.json
      run: |
        if grep -q '"editor.defaultFormatter": "dbaeumer.vscode-eslint"' .vscode/settings.json && grep -q '"eslint.format.enable": true' .vscode/settings.json; then
          echo "ESLint is set as the default formatter and format enable is true."
        else
          echo "Error: ESLint configuration in .vscode/settings.json is incorrect."
          exit 1
        fi

    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
