name: Check code quality
# This trigger runs on every pull request (created,updated) to the main branch. It does not run when a pull request is merged.
on:
  pull_request:
    branches: [main, develop]
    types: [opened, reopened, synchronize, edited]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # This is important to fetch the previous commit as well

    - name: Install dependencies
      run: |
        sudo apt-get install -y jq
        sudo apt-get install -y grep

    - name: Check ESLint configuration in settings.json
      run: |
        if grep -q '"editor.defaultFormatter": "dbaeumer.vscode-eslint"' .vscode/settings.json && grep -q '"eslint.format.enable": true' .vscode/settings.json; then
          echo "ESLint is set as the default formatter and format enable is true."
        else
          echo "Error: ESLint configuration in .vscode/settings.json is incorrect."
          exit 1
        fi

    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
