name: Check code quality
# This trigger runs on every pull request (created,updated) to the main branch. It does not run when a pull request is merged.
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # This is important to fetch the previous commit as well

    - name: Install dependencies
      run: |
        sudo apt-get install -y jq
        sudo apt-get install -y grep

    - name: Check version increase in package.json
      run: |
        # Get the version from the current commit
        CURRENT_VERSION=$(jq -r .version package.json)

        # Checkout the previous commit
        git fetch origin main:main
        git checkout main

        # Get the version from the previous commit
        MAIN_VERSION=$(jq -r .version package.json)

        # Compare the versions
        echo "New version ($CURRENT_VERSION). Main version ($MAIN_VERSION)."
        if [[ "$CURRENT_VERSION" == "$MAIN_VERSION" ]]; then
          echo "Error: Version in package.json has not been increased!"
          exit 1
        else
          echo "Success: Version has been increased successfully!"
        fi
        
    - name: Fetch PR branch latest commit
      run: git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}

    - name: Check if changelog.md has been modified
      run: |
        # Check for changes in changelog.md between main and the current commit
        CHANGED_FILES=$(git diff --name-only main ${{ github.head_ref }} )
        CHANGED=false
        for FILE in $CHANGED_FILES; do
          if [ "$FILE" == "CHANGELOG.md" ]; then
            CHANGED=true
            break
          fi
        done
        if [ "$CHANGED" == "false" ]; then
          echo "Error: changelog.md has not been modified!"
          exit 1
        else
          echo "changelog.md has been modified successfully!"
        fi

  eslint-check:
    runs-on: ubuntu-latest
    needs: check-version
    if: github.base_ref == 'develop' || github.base_ref == 'main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check ESLint configuration in settings.json
      run: |
        if grep -q '"editor.defaultFormatter": "dbaeumer.vscode-eslint"' .vscode/settings.json && grep -q '"eslint.format.enable": true' .vscode/settings.json; then
          echo "ESLint is set as the default formatter and format enable is true."
        else
          echo "Error: ESLint configuration in .vscode/settings.json is incorrect."
          exit 1
        fi

    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
      
